---

- hosts: web_server
  become: true
  tasks:


  - name: remove nginx
    ansible.builtin.dnf:
     name: nginx
     state: absent



  - name: install httpd
    ansible.builtin.dnf:
     name: httpd
     state: latest



  - name: start httpd
    ansible.builtin.service:
     name: httpd
     state: started
     enabled: yes


  - name: copy index.htm
    ansible.builtin.copy:
     src: index.htm
     dest: /var/www/site1
     owner: root
     group: root
     mode: 777
